config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'lists/index'
  get 'lists/new'
  get 'lists/show'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "should be unique per list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmarks_params)
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Successfully added to bookmarks.'
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="p-5 col-3">
<h1>New bookmark</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment, placeholder:'Your comment' %>
    <%= f.submit "Save bookmark", class: "btn btn-success mb-3" %>
  <% end %>

<div>
  <%= link_to "Back to lists", lists_path(@list), class:"text-decoration-none btn btn-primary" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="p-5">
  <%= simple_form_for(@list) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="p-5">
<h1>Lists</h1>
<div class="d-flex">
<% @lists.each do |list| %>
<div class="card m-3 rounded-3 text-center" style="width: 18rem;">
<% if list.photo.attached? %>
  <div class=""
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>')">
    <%= list.name %>
  </div>
  <% end %>
  <div class="card-body">
    <%= link_to "Show this list", list_path(list), class:"text-decoration-none btn btn-primary ms-3" %>
  </div>
</div>
 <% end %>
 </div>
<%= link_to "New list", new_list_path, class:"text-decoration-none btn btn-success" %>
</div>

app/views/lists/new.html.erb
<div class="p-5 col-3">
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path, class:"text-decoration-none btn btn-primary" %>
</div>
</div>

app/views/lists/show.html.erb
<div class="p-5">
  <h3><%= @list.name %></h3>
  <% @list.bookmarks.each do |bookmark| %>
  <div class="card mb-3" style="width: 18rem;">
  <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %>">
  <div class="card-body">
    <h5 class="card-title"><%= bookmark.movie.title %></h5>
    <p class="card-text"><%= bookmark.movie.overview %></p>
    <p class="card-text fw-lighter bg-light fst-italic"><%= bookmark.comment %></p>
    <%= link_to '<i class="fa-solid fa-trash-can ps-2"></i>'.html_safe,
    [@list, bookmark],
    data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
</div>
  <% end %>

<div>
  <%= link_to "Add to bookmarks", new_list_bookmark_path(@list), class:"text-decoration-none btn btn-danger" %>
  <%= link_to "Back to lists", lists_path, class:"text-decoration-none btn btn-primary" %>
</div>
</div>